# Generated by Django 2.1.8 on 2019-04-16 01:22

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='accounts/images'),
        ),
    ]
